use base64::*;
use bevy::{
    app::{PluginsState, RunMode, ScheduleRunnerPlugin},
    prelude::*,
    tasks::tick_global_task_pools_on_main_thread,
};
use bevy_rapier2d::prelude::*;
use player_plugin::InputTracker;
use rust_game_plugin::{logic::rocket::Rocket, *};

mod player_plugin;

fn input_catpure_system(
    input_tracker: Res<InputTracker>,
    keyboard: Res<Input<KeyCode>>,
    rocket_query: Query<(&Rocket, &Transform)>,
) {
    if keyboard.just_pressed(KeyCode::L) && keyboard.pressed(KeyCode::ControlLeft) {
        println!(
            "Inputs({:?}), \n\n\n\n\n\n\n\n\n\n\n\n State({:?})",
            base64::engine::general_purpose::STANDARD
                .encode(bincode::serialize(&input_tracker.into_inner()).unwrap()),
            rocket_query.single().1.translation
        );
    }
}

#[derive(Resource)]
struct InputReplayQueue {
    inputs: Vec<FrameInput>,
}

impl InputReplayQueue {
    fn new(tracker: InputTracker) -> Self {
        Self {
            inputs: tracker.inputs().iter().cloned().rev().collect(),
        }
    }
}

fn validate() {
    let input = "kw4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAEAAAAAAQAAAAABAAAAAAGJiIi8AYmICL0BzsxMvQCJiIi9AKuqqr0AzczMvQDv7u69AImICL4AmpkZvgCrqiq+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74AvLs7vgC8uzu+ALy7O74BvLs7vgG8uzu+Aby7O74BvLs7vgG8uzu+Aby7O74BvLs7vgG8uzu+Aby7O74BvLs7vgG8uzu+Aby7O74BvLs7vgG8uzu+Aby7O74BvLs7vgG8uzu+AauqKr4BmpkZvgGJiAi+AfDu7r0BzszMvQGsqqq9AYqIiL0B0MxMvQGMiAi9AY+IiLwBAABAsgGDiIg8AYaICD0BysxMPQGHiIg9Aamqqj0BqaqqPQGpqqo9Aamqqj0BqaqqPQGpqqo9Aamqqj0BqaqqPQGpqqo9Aamqqj0BqaqqPQGpqqo9Aamqqj0BqaqqPQGpqqo9AYeIiD0BysxMPQGGiAg9AYOIiDwBAABAsgGPiIi8AYyICL0B0MxMvQGKiIi9Aayqqr0BzszMvQHw7u69AYmICL4BmpkZvgGrqiq+Aby7O74BzcxMvgHe3V2+Ae/ubr4BAACAvgGJiIi+ARIRkb4Bm5mZvgGbmZm+AZuZmb4Bm5mZvgGbmZm+AZuZmb4BEhGRvgGJiIi+AQAAgL4B7+5uvgHe3V2+Ac3MTL4BvLs7vgGrqiq+AZqZGb4BiYgIvgHw7u69Ac7MzL0BrKqqvQGKiIi9AdDMTL0BjIgIvQGPiIi8AQAAQLIBg4iIPAGGiAg9AcrMTD0Bh4iIPQGpqqo9AcvMzD0B7e7uPQGIiAg+AZmZGT4BqqoqPgGqqio+AaqqKj4BqqoqPgGqqio+AaqqKj4BqqoqPgGqqio+AaqqKj4BqqoqPgGqqio+AaqqKj4BqqoqPgGqqio+AaqqKj4BqqoqPgGqqio+AZmZGT4BiIgIPgHu7u49AczMzD0BqqqqPQGIiIg9AczMTD0BiIgIPQGHiIg8AQAAgLEBi4iIvAGKiAi9Ac7MTL0BiYiIvQGrqqq9Ac3MzL0B7+7uvQGJiAi+AZqZGb4Bq6oqvgG8uzu+Ac3MTL4B3t1dvgHv7m6+AQAAgL4BiYiIvgESEZG+AZuZmb4Bm5mZvgGbmZm+AZuZmb4Bm5mZvgGbmZm+AZuZmb4Bm5mZvgGbmZm+ASQior4BraqqvgE2M7O+Ab+7u74BSETEvgHRzMy+AVpV1b4B493dvgFsZua+AfXu7r4Bfnf3vgEDAAC/AUdEBL8Bi4gIvwHPzAy/ARMREb8BV1UVvwGbmRm/Ad/dHb8BIyIivwFnZia/AauqKr8B7+4uvwEzMzO/AXd3N78Bu7s7vwG7uzu/Abu7O78Bu7s7vwG7uzu/AXd3N78BMzMzvwHv7i6/AauqKr8BZ2YmvwEjIiK/Ad/dHb8Bm5kZvwFXVRW/ARMREb8Bz8wMvwGLiAi/AUdEBL8BAwAAvwF9d/e+AfTu7r4Ba2bmvgDi3d2+AFlV1b4A0MzMvgBHRMS+AL67u74ANTOzvgCsqqq+ACMior4AmpmZvgAREZG+AIiIiL4A//9/vgDu7m6+AN3dXb4AzMxMvgC7uzu+AKqqKr4AmZkZvgCIiAi+AO7u7r0AzMzMvQCqqqq9AIiIiL0AzMxMvQCIiAi9AIeIiLwAAACAMQCLiIg8AIqICD0AzsxMPQCJiIg9AImIiD0BiYiIPQGJiIg9AYmIiD0BiYiIPQGJiIg9AYmIiD0BiYiIPQGJiIg9AYmIiD0BiYiIPQHOzEw9AYqICD0Bi4iIPAEAAIAxAYeIiLwBiIgIvQHMzEy9AYiIiL0BqqqqvQHMzMy9Ae7u7r0BiIgIvgGZmRm+AaqqKr4Bu7s7vgHMzEy+Ad3dXb4B7u5uvgH//3++AYiIiL4BERGRvgEREZG+AYiIiL4B//9/vgHu7m6+AN3dXb4AzMxMvgC7uzu+AKqqKr4AmZkZvgCIiAi+AO7u7r0AzMzMvQCqqqq9AIiIiL0AzMxMvQCIiAi9AIeIiLwAAACAMQCLiIg8AIqICD0AzsxMPQCJiIg9AKuqqj0AzczMPQDv7u49AImICD4AmpkZPgCrqio+ALy7Oz4AzcxMPgDe3V0+AO/ubj4AAACAPgCJiIg+ARIRkT4Bm5mZPgEkIqI+Aa2qqj4BNjOzPgG/u7s+Ab+7uz4Bv7u7PgG/u7s+Ab+7uz4Bv7u7PgG/u7s+Ab+7uz4Bv7u7PgG/u7s+Ab+7uz4Bv7u7PgG/u7s+Ab+7uz4Bv7u7PgG/u7s+Ab+7uz4Bv7u7PgFIRMQ+AdHMzD4BWlXVPgHj3d0+AWxm5j4B9e7uPgF+d/c+AX539z4Bfnf3PgF+d/c+AX539z4Bfnf3PgF+d/c+AX539z4Bfnf3PgF+d/c+AX539z4Bfnf3PgF+d/c+AX539z4Bfnf3PgF+d/c+AX539z4Bfnf3PgEDAAA/AUdEBD8Bi4gIPwHPzAw/ARMRET8BV1UVPwGbmRk/AZuZGT8Bm5kZPwGbmRk/AZuZGT8Bm5kZPwFXVRU/ARMRET8Bz8wMPwGLiAg/AUdEBD8BAwAAPwF9d/c+AfTu7j4Ba2bmPgHi3d0+AVlV1T4B0MzMPgFHRMQ+Ab67uz4BNTOzPgGsqqo+ASMioj4BmpmZPgEREZE+AYiIiD4B//9/PgHu7m4+Ad3dXT4BzMxMPgG7uzs+AaqqKj4BmZkZPgGIiAg+Ae7u7j0BzMzMPQCqqqo9AIiIiD0AiIiIPQCIiIg9AIiIiD0AiIiIPQDMzEw9AIiICD0Bh4iIPAEAAICxAYuIiLwBiogIvQHOzEy9AYmIiL0Bq6qqvQHNzMy9Ae/u7r0BiYgIvgGamRm+AauqKr4BvLs7vgHNzEy+Ad7dXb4B7+5uvgEAAIC+AYmIiL4BEhGRvgGbmZm+ASQior4BraqqvgE2M7O+Ab+7u74BSETEvgHRzMy+AVpV1b4B493dvgFsZua+AfXu7r4Bfnf3vgEDAAC/AQMAAL8BAwAAvwEDAAC/AQMAAL8BAwAAvwEDAAC/AQMAAL8BAwAAvwEDAAC/AQMAAL8BAwAAvwEDAAC/AQMAAL8BAwAAvwEDAAC/AQMAAL8BAwAAvwF9d/e+AfTu7r4Ba2bmvgHi3d2+AVlV1b4B0MzMvgFHRMS+Ab67u74BNTOzvgGsqqq+ASMior4BmpmZvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BERGRvgEREZG+ARERkb4BiIiIvgH//3++Ae7ubr4B3d1dvgHMzEy+Abu7O74BqqoqvgGZmRm+AYiICL4B7u7uvQDMzMy9AKqqqr0AiIiIvQDMzEy9AIiICL0AiIgIvQCIiAi9AIiICL0AiIgIvQCIiAi9AIiICL0AiIgIvQCIiAi9AIiICL0AiIgIvQGIiAi9AYiICL0BiIgIvQGIiAi9AYiICL0BiIgIvQGIiAi9AYiICL0BiIgIvQGIiAi9AYiICL0BiIgIvQGIiAi9AYiICL0BiIgIvQGIiAi9AYiICL0BiIgIvQGIiAi9AYiICL0BiIgIvQGHiIi8AQAAgDEBi4iIPAGKiAg9Ac7MTD0BiYiIPQGrqqo9Ac3MzD0B7+7uPQGJiAg+AZqZGT4Bq6oqPgG8uzs+Ac3MTD4B3t1dPgHv7m4+AQAAgD4BiYiIPgGJiIg+AYmIiD4BiYiIPgGJiIg+AImIiD4AiYiIPgCJiIg+AImIiD4AiYiIPgGJiIg+AYmIiD4BiYiIPgGJiIg+AYmIiD4BiYiIPgGJiIg+AYmIiD4BiYiIPgGJiIg+AYmIiD4BiYiIPgGJiIg+AYmIiD4BiYiIPgGJiIg+AImIiD4AiYiIPgGJiIg+AYmIiD4BiYiIPgGJiIg+AYmIiD4BiYiIPgESEZE+AZuZmT4BJCKiPgGtqqo+ATYzsz4Bv7u7PgFIRMQ+AdHMzD4BWlXVPgHj3d0+AWxm5j4A9e7uPgB+d/c+AAMAAD8AR0QEPwCLiAg/AM/MDD8BExERPwFXVRU/AZuZGT8B390dPwEjIiI/AWdmJj8Bq6oqPwHv7i4/ATMzMz8Ad3c3PwC7uzs/AP//Pz8AQ0REPwCHiEg/AMvMTD8BDxFRPwFTVVU/AZeZWT8B291dPwEfImI/AWNmZj8Bp6pqPwHr7m4/AS8zcz8Bc3d3PwG3u3s/Afv/fz8AICKCPwBCRIQ/AGRmhj8AhoiIPwCoqoo/AMrMjD8A7O6OPwAOEZE/ADAzkz8AUlWVPwB0d5c/AJaZmT8AuLubPwDa3Z0/APz/nz8AHiKiPwBARKQ/AGJmpj8AhIioPwCmqqo/AMjMrD8A6u6uPwAMEbE/AC4zsz8AUFW1PwByd7c/AJSZuT8Atru7PwDY3b0/APr/vz8AHCLCPwA+RMQ/AGBmxj8AgojIPwCkqso/AMbMzD8A6O7OPwAKEdE/ACwz0z8ATlXVPwBwd9c/AJKZ2T8AtLvbPwDW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8A1t3dPwDW3d0/ANbd3T8A1t3dPwDW3d0/ANbd3T8A1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B+P/fPwEaIuI/ATxE5D8BXmbmPwGAiOg/AaKq6j8BxMzsPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwDm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwEIEfE/ASoz8z8BTFX1PwFud/c/AZCZ+T8Bsrv7PwHU3f0/Afb//z8BDBEBQAEdIgJAAS4zA0ABP0QEQAFQVQVAAWFmBkABcncHQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABg4gIQAGDiAhAAYOICEABcncHQABhZgZAAFBVBUAAP0QEQAAuMwNAAB0iAkAADBEBQAD2//8/ANTd/T8Asrv7PwCQmfk/AG539z8ATFX1PwAqM/M/AAgR8T8A5u7uPwDEzOw/AaKq6j8BgIjoPwFeZuY/ATxE5D8BGiLiPwH4/98/Adbd3T8BtLvbPwGSmdk/AXB31z8BTlXVPwEsM9M/AQoR0T8B6O7OPwHGzMw/AaSqyj8BgojIPwFgZsY/AT5ExD8BHCLCPwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/Afr/vz8B+v+/PwH6/78/APr/vz8A+v+/PwD6/78/ABwiwj8APkTEPwBgZsY/AIKIyD8ApKrKPwDGzMw/AOjuzj8AChHRPwAsM9M/AE5V1T8AcHfXPwCSmdk/ALS72z8A1t3dPwDW3d0/ANbd3T8A1t3dPwDW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B+P/fPwEaIuI/ATxE5D8BXmbmPwGAiOg/AaKq6j8BxMzsPwHm7u4/AQgR8T8BKjPzPwFMVfU/AW539z8BkJn5PwGyu/s/AdTd/T8B9v//PwEMEQFAAR0iAkABLjMDQAE/RARAAVBVBUABYWYGQAFydwdAAYOICEABlJkJQAGlqgpAAba7C0ABtrsLQAG2uwtAAba7C0ABtrsLQAG2uwtAAba7C0ABtrsLQAG2uwtAALa7C0AAtrsLQAC2uwtAALa7C0AAtrsLQAC2uwtAALa7C0AAtrsLQAC2uwtAALa7C0AAtrsLQAC2uwtAAba7C0ABtrsLQAG2uwtAAba7C0ABtrsLQAG2uwtAAba7C0ABtrsLQAG2uwtAAba7C0ABtrsLQAG2uwtAAba7C0ABtrsLQAG2uwtAAaWqCkABlJkJQAGDiAhAAXJ3B0AAYWYGQABQVQVAAD9EBEAALjMDQAAdIgJAAAwRAUAA9v//PwDU3f0/AbK7+z8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwBud/c/AExV9T8AKjPzPwAIEfE/AObu7j8AxMzsPwCiquo/AICI6D8AXmbmPwA8ROQ/ARoi4j8B+P/fPwHW3d0/AbS72z8BkpnZPwFwd9c/AXB31z8BcHfXPwFwd9c/AXB31z8BcHfXPwFwd9c/AXB31z8BcHfXPwFwd9c/AXB31z8BcHfXPwFwd9c/AXB31z8BcHfXPwFwd9c/AZKZ2T8BtLvbPwHW3d0/Afj/3z8BGiLiPwE8ROQ/AV5m5j8BgIjoPwGiquo/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwGiquo/AYCI6D8BXmbmPwE8ROQ/ARoi4j8BGiLiPwEaIuI/ARoi4j8BGiLiPwEaIuI/ARoi4j8BGiLiPwEaIuI/ARoi4j8BGiLiPwAaIuI/ABoi4j8AGiLiPwAaIuI/ABoi4j8AGiLiPwEaIuI/ARoi4j8BGiLiPwEaIuI/ARoi4j8BGiLiPwEaIuI/ARoi4j8BPETkPwFeZuY/AYCI6D8BoqrqPwHEzOw/Aebu7j8B5u7uPwHm7u4/Aebu7j8B5u7uPwHm7u4/Aebu7j8A5u7uPwDm7u4/AObu7j8A5u7uPwHm7u4/Aebu7j8B5u7uPwEIEfE/ASoz8z8BKjPzPwEqM/M/ASoz8z8AKjPzPwAqM/M/ACoz8z8AKjPzPwAqM/M/ACoz8z8BTFX1PwFud/c/AZCZ+T8Bsrv7PwHU3f0/Afb//z8BDBEBQAEdIgJAAR0iAkABHSICQAEdIgJAAR0iAkABHSICQAEdIgJAAR0iAkAAHSICQAAdIgJAAB0iAkAAHSICQAAdIgJAAB0iAkABHSICQAEdIgJAAR0iAkABHSICQAEdIgJAAQwRAUAB9v//PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwHU3f0/AdTd/T8B1N39PwDU3f0/ANTd/T8A1N39PwDU3f0/ALK7+z8AkJn5PwBud/c/AUxV9T8BKjPzPwEIEfE/Aebu7j8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8AxMzsPwDEzOw/AMTM7D8AxMzsPwDEzOw/AMTM7D8AxMzsPwDEzOw/AMTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHEzOw/AcTM7D8BxMzsPwHm7u4/AQgR8T8BKjPzPwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AUxV9T8BTFX1PwFMVfU/AW539z8BkJn5PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AbK7+z8Bsrv7PwGyu/s/AZCZ+T8Bbnf3PwFMVfU/ASoz8z8BCBHxPwHm7u4/AcTM7D8BoqrqPwGiquo/AaKq6j8BoqrqPwGiquo/AaKq6j8BoqrqPwGiquo/AaKq6j8BoqrqPwGiquo/AaKq6j8BoqrqPwGiquo/AaKq6j8BoqrqPwGiquo/AaKq6j8BoqrqPwGiquo/AaKq6j8BoqrqPwGiquo/AaKq6j8BoqrqPwGiquo/AcTM7D8B5u7uPwEIEfE/ASoz8z8BTFX1PwFud/c/AZCZ+T8Bsrv7PwHU3f0/Afb//z8BDBEBQAEdIgJAAS4zA0ABP0QEQAE/RARAAT9EBEABP0QEQAE/RARAAT9EBEABP0QEQAE/RARAAT9EBEABP0QEQAE/RARAAT9EBEABP0QEQAE/RARAAT9EBEABP0QEQAE/RARAAT9EBEABP0QEQAE/RARAAT9EBEAAP0QEQAA/RARAAD9EBEAAP0QEQAA/RARAAD9EBEAAP0QEQAA/RARAAD9EBEAAP0QEQAA/RARAAD9EBEAAP0QEQAA/RARAAD9EBEAAP0QEQAE/RARAAS4zA0ABHSICQAEMEQFAAfb//z8B1N39PwGyu/s/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AJCZ+T8AkJn5PwCQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwCQmfk/AJCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwGQmfk/AZCZ+T8BkJn5PwFud/c/AUxV9T8BKjPzPwEIEfE/AObu7j8AxMzsPwCiquo/AICI6D8AXmbmPwA8ROQ/ABoi4j8A+P/fPwDW3d0/ALS72z8AkpnZPwBwd9c/AE5V1T8ALDPTPwAKEdE/AOjuzj8AxszMPwCkqso/AIKIyD8AYGbGPwE+RMQ/ARwiwj8B+v+/PwHY3b0/Aba7uz8BlJm5PwFyd7c/AVBVtT8BLjOzPwEMEbE/Aerurj8ByMysPwGmqqo/AYSIqD8BYmamPwFiZqY/AWJmpj8BYmamPwFiZqY/AYSIqD8BpqqqPwHIzKw/Aerurj8BDBGxPwEuM7M/AVBVtT8Bcne3PwGUmbk/Aba7uz8B2N29PwH6/78/ARwiwj8BPkTEPwFgZsY/AYKIyD8BpKrKPwHGzMw/Aejuzj8BChHRPwEsM9M/AU5V1T8BcHfXPwGSmdk/AbS72z8B1t3dPwH4/98/ARoi4j8BPETkPwE8ROQ/ATxE5D8BPETkPwE8ROQ/ATxE5D8BPETkPwE8ROQ/ATxE5D8BPETkPwE8ROQ/ATxE5D8BPETkPwE8ROQ/ATxE5D8BPETkPwE8ROQ/ATxE5D8BGiLiPwH4/98/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwHW3d0/Adbd3T8B1t3dPwH4/98/ARoi4j8BPETkPwFeZuY/AYCI6D8BoqrqPwHEzOw/Aebu7j8BCBHxPwEIEfE/AQgR8T8B5u7uPwHEzOw/AaKq6j8BgIjoPwFeZuY/ATxE5D8BGiLiPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/Afj/3z8B+P/fPwH4/98/ARoi4j8BPETkPwFeZuY/AYCI6D8BoqrqPwHEzOw/Aebu7j8BCBHxPwEqM/M/AUxV9T8Bbnf3PwGQmfk/AbK7+z8B1N39PwH2//8/AQwRAUABHSICQAEuMwNAAT9EBEABUFUFQAFhZgZAAXJ3B0ABcncHQAFydwdAAXJ3B0ABcncHQAFydwdAAXJ3B0ABcncHQAFydwdAAXJ3B0ABcncHQAFydwdAAYOICEABlJkJQAGlqgpAAba7C0ABx8wMQAHY3Q1AAenuDkAB+v8PQAELERFAARwiEkABLTMTQAE+RBRAAU9VFUABYGYWQAFxdxdAAYKIGEABk5kZQAGkqhpAAbW7G0ABxswcQAHX3R1AAejuHkAB+f8fQAEKESFAARsiIkABLDMjQAE9RCRAAU5VJUABX2YmQAFwdydAAYGIKEABkpkpQAGjqipAAbS7K0ABxcwsQAHW3S1AAefuLkAB+P8vQAEJETFAARoiMkABKzMzQAE8RDRAAU1VNUABXmY2QAFvdzdAAYCIOEAAkZk5QACiqjpAALO7O0AAxMw8QADV3T1AAObuPkAA9/8/QAAIEUFAARkiQkABKjNDQAE7RERAAUxVRUABXWZGQAFud0dAAX+ISEABkJlJQAGhqkpAAbK7S0ABw8xMQAHU3U1AAeXuTkAB9v9PQAEHEVFAARgiUkABKTNTQAE6RFRAAUtVVUABXGZWQAFtd1dAAX6IWEABj5lZQAGgqlpAAbG7W0ABwsxcQAHT3V1AAeTuXkAB9f9fQAHk7l5AAdPdXUABwsxcQAGxu1tAAaCqWkABj5lZQAGPmVlAAY+ZWUABj5lZQAGPmVlAAY+ZWUABj5lZQAGPmVlAAY+ZWUABj5lZQAGPmVlAAY+ZWUABj5lZQAGPmVlAAY+ZWUABj5lZQAGPmVlAAY+ZWUABj5lZQAGPmVlAAY+ZWUABj5lZQAGPmVlAAY+ZWUABfohYQAFtd1dAAVxmVkABS1VVQAE6RFRAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAE6RFRAAUtVVUABXGZWQAFtd1dAAX6IWEABj5lZQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAaCqWkABoKpaQAGgqlpAAY+ZWUABfohYQAFtd1dAAVxmVkABS1VVQAE6RFRAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAEpM1NAASkzU0ABKTNTQAApM1NAACkzU0AAKTNTQAApM1NAACkzU0AAKTNTQAApM1NAACkzU0AAKTNTQAApM1NAACkzU0AAKTNTQAApM1NAACkzU0AAKTNTQAApM1NAASkzU0ABKTNTQAE6RFRAAUtVVUABXGZWQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0AAbXdXQABtd1dAAG13V0AAbXdXQABtd1dAAG13V0AAbXdXQABtd1dAAG13V0AAbXdXQABtd1dAAG13V0AAbXdXQABtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFtd1dAAW13V0ABbXdXQAFcZlZAAUtVVUABOkRUQAEpM1NAARgiUkABBxFRQAH2/09AAfb/T0AB9v9PQAH2/09AAfb/T0AB9v9PQAH2/09AAfb/T0AB9v9PQAH2/09AAfb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAD2/09AAPb/T0AA9v9PQAAHEVFAARgiUkABKTNTQAE6RFRAAUtVVUABXGZWQAFtd1dAAX6IWEABj5lZQAGgqlpAAbG7W0ABwsxcQAHT3V1AAeTuXkAB9f9fQAEGEWFAARciYkABKDNjQAE5RGRAAUpVZUABW2ZmQAFsd2dAAX2IaEABjplpQAGfqmpAALC7a0AAwcxsQADS3W1AAOPubkAA9P9vQAAFEXFAABYickABJzNzQAE4RHRAAUlVdUABWmZ2QAFrd3dAAXyIeEABfIh4QAF8iHhAAXyIeEABfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAB8iHhAAHyIeEAAfIh4QAFrd3dAAVpmdkABSVV1QAE4RHRAASczc0ABFiJyQAEFEXFAAfT/b0AB4+5uQAHS3W1AAcHMbEABsLtrQAGfqmpAAY6ZaUABfYhoQAFsd2dAAVtmZkABSlVlQAE5RGRAASgzY0AAFyJiQAAGEWFAAPX/X0AA5O5eQADT3V1AAMLMXEAAsbtbQACgqlpAAI+ZWUAAfohYQABtd1dAAFxmVkABS1VVQAE6RFRAASkzU0ABGCJSQAEHEVFAAfb/T0AB5e5OQAHU3U1AAcPMTEABsrtLQAGhqkpAAZCZSUABf4hIQAFud0dAAV1mRkABTFVFQAE7RERAASozQ0ABGSJCQAEIEUFAAff/P0AB5u4+QAHV3T1AAcTMPEABs7s7QAGiqjpAAZGZOUABgIg4QAFvdzdAAV5mNkABTVU1QAA8RDRAACszM0AAGiIyQAAJETFAAPj/L0AA5+4uQADW3S1AAMXMLEAAtLsrQAGjqipAAZKZKUABgYgoQAFwdydAAV9mJkABTlUlQAE9RCRAASwzI0ABGyIiQAEKESFAAfn/H0AB6O4eQAHX3R1AAcbMHEABtbsbQAGkqhpAAZOZGUABgogYQAFxdxdAAWBmFkABT1UVQAE+RBRAAT5EFEABPkQUQAE+RBRAAU9VFUABYGYWQAFxdxdAAYKIGEABk5kZQAGkqhpAAbW7G0ABxswcQAHX3R1AAejuHkAB+f8fQAEKESFAARsiIkABLDMjQAE9RCRAAU5VJUABX2YmQAFwdydAAYGIKEABkpkpQAGjqipAAbS7K0ABxcwsQAHW3S1AAefuLkAB+P8vQAEJETFAARoiMkABKzMzQAE8RDRAAU1VNUABXmY2QAFvdzdAAYCIOEABkZk5QAGiqjpAAbO7O0ABxMw8QAHV3T1AAebuPkAB9/8/QAEIEUFAAQgRQUAB9/8/QAHm7j5AAdXdPUABxMw8QAGzuztAAaKqOkABkZk5QAGAiDhAAYCIOEABgIg4QAGAiDhAAYCIOEABgIg4QAFvdzdAAV5mNkABTVU1QAE8RDRAASszM0ABGiIyQAEJETFAAQkRMUABCRExQAEJETFAAQkRMUABCRExQAEJETFAARoiMkABKzMzQAE8RDRAAU1VNUABXmY2QAFvdzdAAYCIOEABkZk5QACiqjpAALO7O0AAxMw8QADEzDxAAMTMPEAAxMw8QADEzDxAAMTMPEAAxMw8QADEzDxAAMTMPEAAxMw8QADEzDxAAMTMPEAAxMw8QADEzDxAAMTMPEAAxMw8QADEzDxAALO7O0AAoqo6QACRmTlAAICIOEAAb3c3QABeZjZAAE1VNUAAPEQ0QAArMzNAABoiMkAACRExQAH4/y9AAefuLkAB1t0tQAHFzCxAAbS7K0ABo6oqQAGSmSlAAYGIKEABcHcnQAFfZiZAAU5VJUABPUQkQAEsMyNAARsiIkABChEhQAEKESFAAQoRIUABChEhQAAKESFAAAoRIUAAChEhQAAKESFAAAoRIUAAChEhQAAKESFAAAoRIUAA+f8fQADo7h5AANfdHUAAxswcQAC1uxtAAKSqGkAAk5kZQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAIKIGEAAgogYQACCiBhAAJOZGUAApKoaQAC1uxtAAMbMHEAA190dQADo7h5AAOjuHkAA6O4eQADo7h5AAOjuHkAA6O4eQADo7h5AAOjuHkAA6O4eQADo7h5AAOjuHkAA6O4eQADo7h5AAejuHkAB190dQAHGzBxAAbW7G0ABpKoaQAGTmRlAAYKIGEABcXcXQAFgZhZAAU9VFUABPkQUQAEtMxNAARwiEkABCxERQAH6/w9AAenuDkAB2N0NQAHHzAxAAba7C0ABpaoKQAGUmQlAAYOICEABcncHQAFhZgZAAFBVBUAAP0QEQAAuMwNAAB0iAkAADBEBQAD2//8/ANTd/T8Asrv7PwCQmfk/AG539z8ATFX1PwAqM/M/AAgR8T8A5u7uPwDEzOw/AKKq6j8AgIjoPwBeZuY/ADxE5D8AGiLiPwD4/98/ANbd3T8AtLvbPwCSmdk/AHB31z8ATlXVPwAsM9M/AAoR0T8A6O7OPwDGzMw/AKSqyj8ApKrKPwCkqso/AKSqyj8ApKrKPwCkqso/AIKIyD8AYGbGPwA+RMQ/ABwiwj8A+v+/PwDY3b0/ALa7uz8BlJm5PwFyd7c/AVBVtT8BLjOzPwEMEbE/Aerurj8ByMysPwGmqqo/AYSIqD8BYmamPwFARKQ/AR4ioj8B/P+fPwHa3Z0/Abi7mz8BlpmZPwF0d5c/AVJVlT8BMDOTPwEOEZE/AOzujj8AysyMPwCoqoo/AIaIiD8AZGaGPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwBCRIQ/AEJEhD8AQkSEPwFCRIQ/AUJEhD8BQkSEPwFCRIQ/AUJEhD8BICKCPwH8/38/Abi7ez8BdHd3PwEwM3M/Aezubj8BqKpqPwFkZmY/ASAiYj8B3N1dPwGYmVk/AVRVVT8BEBFRPwHMzEw/AYiISD8BREREPwEAAEA/ALy7Oz8AeHc3PwA0MzM/APDuLj8ArKoqPwBoZiY/ACQiIj8A4N0dPwGcmRk/AVhVFT8BFBERPwHQzAw/AYyICD8BSEQEPwEEAAA/AX939z4B9u7uPgFtZuY+AeTd3T4BW1XVPgHSzMw+AUlExD4BwLu7PgE3M7M+Aa6qqj4BJSKiPgGcmZk+ARMRkT4BioiIPgEBAIA+AfHubj4B4N1dPgHPzEw+Ab67Oz4BraoqPgGcmRk+AYuICD4B9O7uPQHSzMw9AbCqqj0BjoiIPQHYzEw9AZSICD0Bn4iIPAEAADAzAQAAMDMBAAAwMwEAADAzAQAAMDMBAAAwMwEAADAzAQAAMDMAAAAwMwAAADAzAAAAMDMAAAAwMwAAADAzAAAAMDMAn4iIPACUiAg9ANjMTD0AjoiIPQCwqqo9ANLMzD0A9O7uPQCLiAg+AJyZGT4AraoqPgC+uzs+AM/MTD4B4N1dPgHx7m4+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BAQCAPgEBAIA+AQEAgD4BioiIPgETEZE+AZyZmT4BJSKiPgGuqqo+ATczsz4BwLu7PgFJRMQ+AdLMzD4BW1XVPgHk3d0+AW1m5j4B9u7uPgF/d/c+AQQAAD8BSEQEPwGMiAg/AdDMDD8BFBERPwEUERE/ARQRET8BFBERPwEUERE/ARQRET8BFBERPwEUERE/ARQRET8BFBERPwEUERE/ARQRET8BFBERPwEUERE/ARQRET8BFBERPwEUERE/ABQRET8A0MwMPwCMiAg/AEhEBD8ABAAAPwB/d/c+APbu7j4AbWbmPgDk3d0+AFtV1T4A0szMPgBJRMQ+AMC7uz4ANzOzPgCuqqo+ACUioj4AnJmZPgATEZE+AIqIiD4AAQCAPgDx7m4+AODdXT4Az8xMPgC+uzs+AK2qKj4AnJkZPgCLiAg+APTu7j0A0szMPQCwqqo9AI6IiD0A2MxMPQDYzEw9ANjMTD0A2MxMPQDYzEw9ANjMTD0A2MxMPQDYzEw9ANjMTD0A2MxMPQDYzEw9ANjMTD0A2MxMPQDYzEw9ANjMTD0A2MxMPQCUiAg9AJ+IiDwAAAAwMwBziIi8AH6ICL0AwsxMvQCDiIi9AKWqqr0Ax8zMvQDp7u69AIaICL4Al5kZvgCoqiq+ALm7O74AysxMvgDb3V2+AOzubr4A/f9/vgCHiIi+ABARkb4AmZmZvgAiIqK+AKuqqr4ANDOzvgC9u7u+AEZExL4Az8zMvgBYVdW+AOHd3b4AambmvgDz7u6+AHx3974AAgAAvwBGRAS/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8AiogIvwCKiAi/AIqICL8A";
    let target = Vec3::new(-23.770296, 35.94703, 0.0);

    let input_tracker: InputTracker = bincode::deserialize(
        &base64::engine::general_purpose::STANDARD
            .decode(input)
            .unwrap(),
    )
    .unwrap();

    let mut app = App::new();

    let map = "CscCCgZOb3JtYWwSvAIKCg2F65XBFTXTGkISKA2kcLrBFZfjFkIlAAAAwi1SuIlCNa5H+UE9H4X/QUUAAABATQAAAEASKA1SuMFBFZmRGkIlhetRQS3NzFJCNSlcp0I9zcxEQUUAAABATQAAAEASKA0AgEVCFfIboEElAAAoQi0K189BNaRw4UI9rkdZwUUAAABATQAAAEASKA171MBCFcubHcElmpm5Qi0K189BNY/CI0M9rkdZwUUAAABATQAAAEASLQ1syOFCFToytkEdVGuzOiWamblCLSlcZUI1XI8jQz3NzIhBRQAAAEBNAAAAQBItDR/lAUMVk9VNQh2fUDa1JaRw9UItexRsQjWF60FDPQAAlEFFAAAAQE0AAABAEigNw1UzQxVpqkFCJdejJEMtBW94QjXXo0JDPQVvAEJFAAAAQE0AAABACu4KCg1Ob3JtYWwgU2hhcGVzEtwKGt8GCtwGP4UAws3MNEGgEEAAZjYAAP///wB1PAAU////AF5PABT///8AyUtPxP///wAzSg3L////AMBJAcj///8AE0Umzf///wCMVAo5////AJNRpDr///8AVE0WVP///wD0vlZLAAD/AEPI7Bn///8AhcPlOAAA/wAFQZrF////ADS9F8f///8AJMIuwf///wC5xvvF////AOrJ1rf///8Ac8ikQP///wBAxfRF////AGkxi0n///8Aj0LxQgAA/wB1xWY9////AJ/HZAlQUP4AzcUBvQAA/wDwQFzE////ADDGR73///8As8eZPoiI8QBxxWQ3rKz/AFw3LMQAAP8AwkNRtP///wC2RKO4////AEhBe8EAAP8AS0WPPP///wAdSaSx////AMw/Ucj///8A7MBNxv///wDmxnG9////AELCFLr///8Aw8UOof///wAKxCg4AAD/ALg8OMDZ2fsA4j9NwP///wCkxB+/AADwAHGwrr54ePgAVERcwv///wAPwXbA////APW0H0EAAPgASLtnv////wALM67DJSX/AFJApL////8AZj4uwP///wBcu+HATU3/AIU7+8H///8AXMK8Lf///wB7wjM/AAD4AHDCx8D///8AFEH7wP///wAAvnvE////AOTGChL///8A6bncRP///wCAQddAAAD4AB/AxLH///8AIL9RPQAA+ACZwqvG////AOLCLkQAAPgAIcTrwP///wDtwQPH////AOLJbqz///8ALsR6QwAA+AD+x8zA////APtF90kyMv8AH7mZQCcn/wCNxHo8tbX/AIDAiETKyv8AXEAgSgAA+AClyAqS////AH9EG0n///8AS0ypRP///wAxSIK7MDToANjBdUf///8A58yjxP///wCByD1EMDToAIzCYMv///8AnMq3MzA06AC+QenF////ANzGT0T///8AtMFSR////wBzRb85lpj/AFJALEQwNOgAqMIpPjA06AAgyiCF////AAPEE77///8AzT4FSnN1/wAzxWFCMDToAA23PcKXl/8AGcLmQDA06ADMPUnJu77/AFrGxsL///8A1TRGSjA06ACKwik8MDToAE3Apcn///8Ar8SawP///wBsygqP////ABHI8z0wNOgAAABTzv///wAa9wMK9APNzJNCj8JlQP///wBmtly8////ABa2jsg2Nv8AO0SENwAA+ACkvrtEvLz/AG0uOEX///8A4UaHPv///wA+QlXFAAD4AApB2L4AAPgAeDLVRP///wATSHHAAAD4ADhA3EP///8As0MKvAAA8ADOPxM4AAD4AEjBTUD///8Arj5TP3B0+ACyKw9DaGz4ALm6eDz///8AKT4MSP///wDhPy5CAAD/APS/XEL///8A+EV6PwAA/wAdsXtBp6f/AGzEpEEAAP8AisfEuf///wDXwVJI////AJpEaUf///8AhUfxQP///wB7RA3FAAD/ANdBTzUAAP8AC8C9Rv///wBGQoVE////APRMpDz///8A7kS3yAAA/wDLR9HB////AFLHNscAAP8AR0HNwf///wDsvtLGAAD/AABE5kD///8AD0JIRv///wD0RNJA////AEVFqcD///8A3ESpwwAA/wAuwgtJ////AARBqEj///8ALUdbSf///wA01Hks////AHjCAL3///8AF8s5x////wC4vlPP////AME1O8f///8AhsIAPgAA+ABcxZXC7e3/AIrEpUMAAPgAjcbDxcvL/wBdQFzF////AEjI+8EAAOAAQ0GZvf///wAGN77AFRX/APlFXDz///8AikEzwkhI+ADcQmoy////AArNAgoHUmV2ZXJzZRLBAgoPDRydLkMVk5lFQh2z7Zk2EigNpHC6wRWX4xZCJQAAAMItAABMQjUAAEDBPR+F/0FFAAAAQE0AAABAEigNUrjBQRWZkRpCJR+FAMItZuaJQjUAAPpBPQAAAEJFAAAAQE0AAABAEigNAIBFQhXyG6BBJQAAUEEthetRQjWkcKdCPVK4TkFFAAAAQE0AAABAEigNe9TAQhXLmx3BJTQzKEItCtfPQTUeBeJCPa5HWcFFAAAAQE0AAABAEi0NbMjhQhU6MrZBHVRrszolmpm5Qi1SuNRBNVyPI0M9ZmZawUUAAABATQAAAEASLQ0f5QFDFZPVTUIdn1A2tSWk8LlCLXsUZUI1hSskQz0AAIZBRQAAAEBNAAAAQBIoDcNVM0MVaapBQiUAgPVCLQAAbEI1AABCQz0AAJRBRQAAAEBNAAAAQBIhCgZOb3JtYWwSFwoNTm9ybWFsIFNoYXBlcwoGTm9ybWFsEiMKB1JldmVyc2USGAoNTm9ybWFsIFNoYXBlcwoHUmV2ZXJzZQ==";
    let map_template = MapTemplate::new(map, "Normal");

    app.add_plugins(MinimalPlugins);

    app.set_runner(move |mut app: App| {
        while app.plugins_state() == PluginsState::Adding {
            #[cfg(not(target_arch = "wasm32"))]
            tick_global_task_pools_on_main_thread();
        }

        app.finish();
        app.cleanup();

        app.update();
    });

    app.insert_resource(map_template)
        .add_plugins(GamePlugin::default().in_schedule(Update));

    app.world
        .resource_scope(|_: &mut World, mut input_events: Mut<Events<FrameInput>>| {
            for input in input_tracker.inputs() {
                println!("Input");
                input_events.send(input.clone());
            }
        });

    while app.plugins_state() == PluginsState::Adding {
        #[cfg(not(target_arch = "wasm32"))]
        tick_global_task_pools_on_main_thread();
    }

    app.finish();
    app.cleanup();

    app.update();
    app.update();
    app.update();

    let current_target = app
        .world
        .query::<(&Transform, &Rocket)>()
        .single(&app.world)
        .0;

    if current_target.translation != target {
        panic!("old: ({})new: ({})", target, current_target.translation);
    } else {
        panic!("The target has not changed!");
    }
}

pub fn main() {
    validate();

    let mut app = App::new();

    let map = "CscCCgZOb3JtYWwSvAIKCg2F65XBFTXTGkISKA2kcLrBFZfjFkIlAAAAwi1SuIlCNa5H+UE9H4X/QUUAAABATQAAAEASKA1SuMFBFZmRGkIlhetRQS3NzFJCNSlcp0I9zcxEQUUAAABATQAAAEASKA0AgEVCFfIboEElAAAoQi0K189BNaRw4UI9rkdZwUUAAABATQAAAEASKA171MBCFcubHcElmpm5Qi0K189BNY/CI0M9rkdZwUUAAABATQAAAEASLQ1syOFCFToytkEdVGuzOiWamblCLSlcZUI1XI8jQz3NzIhBRQAAAEBNAAAAQBItDR/lAUMVk9VNQh2fUDa1JaRw9UItexRsQjWF60FDPQAAlEFFAAAAQE0AAABAEigNw1UzQxVpqkFCJdejJEMtBW94QjXXo0JDPQVvAEJFAAAAQE0AAABACu4KCg1Ob3JtYWwgU2hhcGVzEtwKGt8GCtwGP4UAws3MNEGgEEAAZjYAAP///wB1PAAU////AF5PABT///8AyUtPxP///wAzSg3L////AMBJAcj///8AE0Umzf///wCMVAo5////AJNRpDr///8AVE0WVP///wD0vlZLAAD/AEPI7Bn///8AhcPlOAAA/wAFQZrF////ADS9F8f///8AJMIuwf///wC5xvvF////AOrJ1rf///8Ac8ikQP///wBAxfRF////AGkxi0n///8Aj0LxQgAA/wB1xWY9////AJ/HZAlQUP4AzcUBvQAA/wDwQFzE////ADDGR73///8As8eZPoiI8QBxxWQ3rKz/AFw3LMQAAP8AwkNRtP///wC2RKO4////AEhBe8EAAP8AS0WPPP///wAdSaSx////AMw/Ucj///8A7MBNxv///wDmxnG9////AELCFLr///8Aw8UOof///wAKxCg4AAD/ALg8OMDZ2fsA4j9NwP///wCkxB+/AADwAHGwrr54ePgAVERcwv///wAPwXbA////APW0H0EAAPgASLtnv////wALM67DJSX/AFJApL////8AZj4uwP///wBcu+HATU3/AIU7+8H///8AXMK8Lf///wB7wjM/AAD4AHDCx8D///8AFEH7wP///wAAvnvE////AOTGChL///8A6bncRP///wCAQddAAAD4AB/AxLH///8AIL9RPQAA+ACZwqvG////AOLCLkQAAPgAIcTrwP///wDtwQPH////AOLJbqz///8ALsR6QwAA+AD+x8zA////APtF90kyMv8AH7mZQCcn/wCNxHo8tbX/AIDAiETKyv8AXEAgSgAA+AClyAqS////AH9EG0n///8AS0ypRP///wAxSIK7MDToANjBdUf///8A58yjxP///wCByD1EMDToAIzCYMv///8AnMq3MzA06AC+QenF////ANzGT0T///8AtMFSR////wBzRb85lpj/AFJALEQwNOgAqMIpPjA06AAgyiCF////AAPEE77///8AzT4FSnN1/wAzxWFCMDToAA23PcKXl/8AGcLmQDA06ADMPUnJu77/AFrGxsL///8A1TRGSjA06ACKwik8MDToAE3Apcn///8Ar8SawP///wBsygqP////ABHI8z0wNOgAAABTzv///wAa9wMK9APNzJNCj8JlQP///wBmtly8////ABa2jsg2Nv8AO0SENwAA+ACkvrtEvLz/AG0uOEX///8A4UaHPv///wA+QlXFAAD4AApB2L4AAPgAeDLVRP///wATSHHAAAD4ADhA3EP///8As0MKvAAA8ADOPxM4AAD4AEjBTUD///8Arj5TP3B0+ACyKw9DaGz4ALm6eDz///8AKT4MSP///wDhPy5CAAD/APS/XEL///8A+EV6PwAA/wAdsXtBp6f/AGzEpEEAAP8AisfEuf///wDXwVJI////AJpEaUf///8AhUfxQP///wB7RA3FAAD/ANdBTzUAAP8AC8C9Rv///wBGQoVE////APRMpDz///8A7kS3yAAA/wDLR9HB////AFLHNscAAP8AR0HNwf///wDsvtLGAAD/AABE5kD///8AD0JIRv///wD0RNJA////AEVFqcD///8A3ESpwwAA/wAuwgtJ////AARBqEj///8ALUdbSf///wA01Hks////AHjCAL3///8AF8s5x////wC4vlPP////AME1O8f///8AhsIAPgAA+ABcxZXC7e3/AIrEpUMAAPgAjcbDxcvL/wBdQFzF////AEjI+8EAAOAAQ0GZvf///wAGN77AFRX/APlFXDz///8AikEzwkhI+ADcQmoy////AArNAgoHUmV2ZXJzZRLBAgoPDRydLkMVk5lFQh2z7Zk2EigNpHC6wRWX4xZCJQAAAMItAABMQjUAAEDBPR+F/0FFAAAAQE0AAABAEigNUrjBQRWZkRpCJR+FAMItZuaJQjUAAPpBPQAAAEJFAAAAQE0AAABAEigNAIBFQhXyG6BBJQAAUEEthetRQjWkcKdCPVK4TkFFAAAAQE0AAABAEigNe9TAQhXLmx3BJTQzKEItCtfPQTUeBeJCPa5HWcFFAAAAQE0AAABAEi0NbMjhQhU6MrZBHVRrszolmpm5Qi1SuNRBNVyPI0M9ZmZawUUAAABATQAAAEASLQ0f5QFDFZPVTUIdn1A2tSWk8LlCLXsUZUI1hSskQz0AAIZBRQAAAEBNAAAAQBIoDcNVM0MVaapBQiUAgPVCLQAAbEI1AABCQz0AAJRBRQAAAEBNAAAAQBIhCgZOb3JtYWwSFwoNTm9ybWFsIFNoYXBlcwoGTm9ybWFsEiMKB1JldmVyc2USGAoNTm9ybWFsIFNoYXBlcwoHUmV2ZXJzZQ==";
    let map_template = MapTemplate::new(map, "Normal");

    app.add_plugins(DefaultPlugins)
        .add_plugins(RapierDebugRenderPlugin::default());

    app.insert_resource(map_template)
        .add_plugins(GamePlugin::default())
        .add_plugins(player_plugin::PlayerPlugin::default());

    app.add_systems(PostUpdate, input_catpure_system);

    app.run();
}

/*
use std::borrow::Borrow;

use base64::Engine;
use bevy::{prelude::*, window::PrimaryWindow};
use bevy_prototype_lyon::{
    entity::Path, geometry::GeometryBuilder, prelude::tess::path::PathEvent, shapes,
};
use bevy_rapier2d::prelude::*;
use prost::Message;
use rapier2d::math::Isometry;
use rust_proto::RocketModel;

mod app;

struct FrameInput {
    pub rotation: f32,
    pub thrust: bool,
}

#[derive(Resource)]
struct FrameInputTrackingResource<'a> {
    pub inputs: &'a mut Vec<FrameInput>,
}

fn main() {
    app::run();

    let mut app = App::new();

    app.add_plugins(DefaultPlugins)
        .add_plugins(RapierPhysicsPlugin::<NoUserData>::pixels_per_meter(1.0).in_fixed_schedule())
        .add_plugins(RapierDebugRenderPlugin::default())
        .add_plugins(GamePlugin)
        .insert_resource(Time::from_hz(60.0));

    app.run();

    for input in app
        .world
        .get_resource::<FrameInputTrackingResource>()
        .unwrap()
        .inputs
        .iter()
    {
        println!("Rotation: {}, Thrust: {}", input.rotation, input.thrust);
    }
}

#[derive(Resource)]
struct MapResource {}

pub struct GamePlugin;

impl Plugin for GamePlugin {
    fn build(&self, app: &mut App) {
        app.insert_resource(MapResource {})
            .insert_resource(RapierConfiguration {
                physics_pipeline_active: true,
                timestep_mode: TimestepMode::Fixed {
                    dt: 1.0 / 60.0,
                    substeps: 1,
                },
                gravity: Vec2::new(0.0, -20.0),
                ..Default::default()
            })
            .add_systems(Startup, init_game_system)
            .add_systems(FixedUpdate, rocket_input.pipe(rocket_input_handler));
    }
}

#[derive(Component, Default)]
struct Rocket {}

#[derive(Bundle, Default)]
struct RocketBundle {
    rocket: Rocket,

    rigid_body: RigidBody,
    collider: Collider,
    colliding_entities: CollidingEntities,

    transform: TransformBundle,
    transform_interpolation: TransformInterpolation,
    external_impulse: ExternalImpulse,
}

#[derive(Component)]
struct Shape {}

#[derive(Bundle)]
struct ShapeBundle {
    rigid_body: RigidBody,
    collider: Collider,
    transform: TransformBundle,
}

fn rocket_collider() -> Option<Collider> {
    let rocket_colliders_vertices = vec![
        vec![
            (-0.894, -1.212),
            (-0.882, -0.33),
            (-0.87, -0.144),
            (-0.834, 0.096),
            (-0.708, 0.588),
            (-0.456, 1.152),
            (-0.198, 1.548),
            (0.00, 1.8),
            (0.198, 1.548),
            (0.456, 1.152),
            (0.708, 0.588),
            (0.834, 0.096),
            (0.87, -0.144),
            (0.882, -0.33),
            (0.894, -1.212),
        ],
        vec![(0.9, -1.8), (0.24, -1.212), (0.894, -1.212)],
        vec![(-0.9, -1.8), (-0.894, -1.212), (-0.24, -1.212)],
    ];

    let rocket_colliders = rocket_colliders_vertices
        .into_iter()
        .map(|points| {
            Collider::convex_hull(
                // floatsarray to vec2 array
                &points
                    .into_iter()
                    .map(|(x, y)| Vec2::new(x, y))
                    .collect::<Vec<Vec2>>(),
            )
        })
        .collect::<Option<Vec<Collider>>>()?;

    let compound = Collider::compound(
        rocket_colliders
            .iter()
            .map(|collider| (Vec2::ZERO, 0.0, collider.clone()))
            .collect(),
    );

    Some(compound)
}

fn init_game_system(mut commands: Commands) {
    let world_str = "CscCCgZOb3JtYWwSvAIKCg2F65XBFTXTGkISKA2kcLrBFZfjFkIlAAAAwi1SuIlCNa5H+UE9H4X/QUUAAABATQAAAEASKA1SuMFBFZmRGkIlhetRQS3NzFJCNSlcp0I9zcxEQUUAAABATQAAAEASKA0AgEVCFfIboEElAAAoQi0K189BNaRw4UI9rkdZwUUAAABATQAAAEASKA171MBCFcubHcElmpm5Qi0K189BNY/CI0M9rkdZwUUAAABATQAAAEASLQ1syOFCFToytkEdVGuzOiWamblCLSlcZUI1XI8jQz3NzIhBRQAAAEBNAAAAQBItDR/lAUMVk9VNQh2fUDa1JaRw9UItexRsQjWF60FDPQAAlEFFAAAAQE0AAABAEigNw1UzQxVpqkFCJdejJEMtBW94QjXXo0JDPQVvAEJFAAAAQE0AAABACu4KCg1Ob3JtYWwgU2hhcGVzEtwKGt8GCtwGP4UAws3MNEGgEEAAZjYAAP///wB1PAAU////AF5PABT///8AyUtPxP///wAzSg3L////AMBJAcj///8AE0Umzf///wCMVAo5////AJNRpDr///8AVE0WVP///wD0vlZLAAD/AEPI7Bn///8AhcPlOAAA/wAFQZrF////ADS9F8f///8AJMIuwf///wC5xvvF////AOrJ1rf///8Ac8ikQP///wBAxfRF////AGkxi0n///8Aj0LxQgAA/wB1xWY9////AJ/HZAlQUP4AzcUBvQAA/wDwQFzE////ADDGR73///8As8eZPoiI8QBxxWQ3rKz/AFw3LMQAAP8AwkNRtP///wC2RKO4////AEhBe8EAAP8AS0WPPP///wAdSaSx////AMw/Ucj///8A7MBNxv///wDmxnG9////AELCFLr///8Aw8UOof///wAKxCg4AAD/ALg8OMDZ2fsA4j9NwP///wCkxB+/AADwAHGwrr54ePgAVERcwv///wAPwXbA////APW0H0EAAPgASLtnv////wALM67DJSX/AFJApL////8AZj4uwP///wBcu+HATU3/AIU7+8H///8AXMK8Lf///wB7wjM/AAD4AHDCx8D///8AFEH7wP///wAAvnvE////AOTGChL///8A6bncRP///wCAQddAAAD4AB/AxLH///8AIL9RPQAA+ACZwqvG////AOLCLkQAAPgAIcTrwP///wDtwQPH////AOLJbqz///8ALsR6QwAA+AD+x8zA////APtF90kyMv8AH7mZQCcn/wCNxHo8tbX/AIDAiETKyv8AXEAgSgAA+AClyAqS////AH9EG0n///8AS0ypRP///wAxSIK7MDToANjBdUf///8A58yjxP///wCByD1EMDToAIzCYMv///8AnMq3MzA06AC+QenF////ANzGT0T///8AtMFSR////wBzRb85lpj/AFJALEQwNOgAqMIpPjA06AAgyiCF////AAPEE77///8AzT4FSnN1/wAzxWFCMDToAA23PcKXl/8AGcLmQDA06ADMPUnJu77/AFrGxsL///8A1TRGSjA06ACKwik8MDToAE3Apcn///8Ar8SawP///wBsygqP////ABHI8z0wNOgAAABTzv///wAa9wMK9APNzJNCj8JlQP///wBmtly8////ABa2jsg2Nv8AO0SENwAA+ACkvrtEvLz/AG0uOEX///8A4UaHPv///wA+QlXFAAD4AApB2L4AAPgAeDLVRP///wATSHHAAAD4ADhA3EP///8As0MKvAAA8ADOPxM4AAD4AEjBTUD///8Arj5TP3B0+ACyKw9DaGz4ALm6eDz///8AKT4MSP///wDhPy5CAAD/APS/XEL///8A+EV6PwAA/wAdsXtBp6f/AGzEpEEAAP8AisfEuf///wDXwVJI////AJpEaUf///8AhUfxQP///wB7RA3FAAD/ANdBTzUAAP8AC8C9Rv///wBGQoVE////APRMpDz///8A7kS3yAAA/wDLR9HB////AFLHNscAAP8AR0HNwf///wDsvtLGAAD/AABE5kD///8AD0JIRv///wD0RNJA////AEVFqcD///8A3ESpwwAA/wAuwgtJ////AARBqEj///8ALUdbSf///wA01Hks////AHjCAL3///8AF8s5x////wC4vlPP////AME1O8f///8AhsIAPgAA+ABcxZXC7e3/AIrEpUMAAPgAjcbDxcvL/wBdQFzF////AEjI+8EAAOAAQ0GZvf///wAGN77AFRX/APlFXDz///8AikEzwkhI+ADcQmoy////AArNAgoHUmV2ZXJzZRLBAgoPDRydLkMVk5lFQh2z7Zk2EigNpHC6wRWX4xZCJQAAAMItAABMQjUAAEDBPR+F/0FFAAAAQE0AAABAEigNUrjBQRWZkRpCJR+FAMItZuaJQjUAAPpBPQAAAEJFAAAAQE0AAABAEigNAIBFQhXyG6BBJQAAUEEthetRQjWkcKdCPVK4TkFFAAAAQE0AAABAEigNe9TAQhXLmx3BJTQzKEItCtfPQTUeBeJCPa5HWcFFAAAAQE0AAABAEi0NbMjhQhU6MrZBHVRrszolmpm5Qi1SuNRBNVyPI0M9ZmZawUUAAABATQAAAEASLQ0f5QFDFZPVTUIdn1A2tSWk8LlCLXsUZUI1hSskQz0AAIZBRQAAAEBNAAAAQBIoDcNVM0MVaapBQiUAgPVCLQAAbEI1AABCQz0AAJRBRQAAAEBNAAAAQBIhCgZOb3JtYWwSFwoNTm9ybWFsIFNoYXBlcwoGTm9ybWFsEiMKB1JldmVyc2USGAoNTm9ybWFsIFNoYXBlcwoHUmV2ZXJzZQ==";

    let world_bin = base64::engine::general_purpose::STANDARD
        .decode(world_str)
        .unwrap();

    let world = rust_proto::WorldModel::decode(world_bin.as_slice()).unwrap();

    println!("Groups: {:?}", world.groups.keys());

    let RocketModel {
        position_x,
        position_y,
        ..
    } = world.groups["Normal"].rockets.first().unwrap();

    let rocket_path = GeometryBuilder::build_as(&shapes::SvgPathShape {
        svg_path_string: "M 1 502 L 3 355 C 4 344 4 334 5 324 C 7 310 9 297 11 284 C 15 256 23 229 32 202 C 43 169 57 138 74 108 C 87 85 100 62 117 42 L 150 0 L 183 42 C 200 62 213 85 226 108 C 243 138 257 169 268 202 C 277 229 285 256 289 284 C 291 297 293 310 295 324 C 296 334 296 344 297 355 L 299 502 L 300 600 L 190 502 L 110 502 L 0 600 z".to_owned(),
        svg_doc_size_in_px: Vec2::new(300.0, 600.0),
    });

    commands.spawn(Camera2dBundle {
        projection: OrthographicProjection {
            far: 1000.,
            near: -1000.,
            scale: 0.10,
            ..Default::default()
        },
        transform: Transform::from_xyz(*position_x, *position_y, 1.0),
        ..Default::default()
    });

    commands.init_resource::<GameConfig>();

    commands
        .spawn(RocketBundle {
            rigid_body: RigidBody::Dynamic,
            collider: rocket_collider().unwrap(),
            transform: TransformBundle::from(Transform::from_xyz(*position_x, *position_y, 0.0)),
            ..Default::default()
        })
        .insert(ActiveEvents::COLLISION_EVENTS)
        .insert(ColliderMassProperties::Mass(20.0))
        .insert(Damping {
            linear_damping: 0.0,
            angular_damping: 0.5,
        })
        .insert(Ccd::enabled());

    for shape in world.groups["Normal Shapes"].shapes.iter() {
        let mut vertices = Vec::new();

        let mut x: f32 = f32::from_ne_bytes(shape.vertices[0..4].try_into().unwrap());
        let mut y: f32 = f32::from_ne_bytes(shape.vertices[4..8].try_into().unwrap());

        vertices.push(Vec2::new(x, y));

        let mut byteCount = 12;

        while byteCount < shape.vertices.len() {
            x += half::f16::from_ne_bytes([
                shape.vertices[byteCount],
                shape.vertices[byteCount + 1],
            ])
            .to_f32();
            y += half::f16::from_ne_bytes([
                shape.vertices[byteCount + 2],
                shape.vertices[byteCount + 3],
            ])
            .to_f32();

            vertices.push(Vec2::new(x, y));

            byteCount += 8;
        }

        let min_x = vertices.iter().fold(f32::INFINITY, |acc, v| acc.min(v.x));
        let min_y = vertices.iter().fold(f32::INFINITY, |acc, v| acc.min(v.y));

        let indices: Vec<_> = (0..(vertices.len() as u32))
            .map(|x| [x, (x + 1) % vertices.len() as u32] as [u32; 2])
            .collect();

        commands.spawn(ShapeBundle {
            rigid_body: RigidBody::Fixed,
            collider: Collider::convex_decomposition(vertices, None),
            transform: TransformBundle::from(Transform::from_xyz(0.0, 0.0, 0.0)),
        });
    }

    // rectangle of height 3.6
    commands.spawn(ShapeBundle {
        rigid_body: RigidBody::Fixed,
        collider: Collider::cuboid(5.0, 1.8),
        transform: TransformBundle::from(Transform::from_xyz(8.0, -15.0, 0.0)),
    });
}

#[derive(Resource)]
struct GameConfig {
    thrust_distance: f32,
    thrust_value: f32,
    thrust_ground_multiplier: f32,
    explosion_angle: f32,
}

impl Default for GameConfig {
    fn default() -> Self {
        GameConfig {
            thrust_distance: 1.0,
            thrust_value: 7.3,
            thrust_ground_multiplier: 1.3,
            explosion_angle: 0.3,
        }
    }
}

enum InputState {
    Keyboard { rotation: f32 },
}

impl Default for InputState {
    fn default() -> Self {
        InputState::Keyboard { rotation: 0.0 }
    }
}

fn rocket_input(
    mut state: Local<InputState>,
    time: Res<Time>,
    windows: Query<&Window, With<PrimaryWindow>>,
    keyboard: Res<Input<KeyCode>>,
) -> FrameInput {
    match *state {
        InputState::Keyboard { mut rotation } => {
            if keyboard.pressed(KeyCode::Left) {
                rotation += 1.0 * time.delta_seconds();
            }

            if keyboard.pressed(KeyCode::Right) {
                rotation -= 1.0 * time.delta_seconds();
            }

            *state = InputState::Keyboard { rotation };

            FrameInput {
                rotation,
                thrust: keyboard.pressed(KeyCode::Up),
            }
        }
    }
}

struct Times {
    start: std::time::Instant,
    count: usize,
}

impl Default for Times {
    fn default() -> Self {
        Times {
            start: std::time::Instant::now(),
            count: 0,
        }
    }
}

#[derive(Default)]
struct InputHandlerState {
    offset: f32,
}

fn rocket_input_handler(
    In(input): In<FrameInput>,
    mut state: Local<InputHandlerState>,
    mut time: Local<Times>,
    mut rocket_query: Query<
        (
            Entity,
            &CollidingEntities,
            &mut Transform,
            &mut ExternalImpulse,
        ),
        With<Rocket>,
    >,
    game_config: Res<GameConfig>,
    rapier_context: Res<RapierContext>,
) {
    time.count += 1;

    println!(
        "FPS: {}",
        time.count as f32 / time.start.elapsed().as_secs_f32()
    );

    let (entity, colliding_entities, mut rocket_transform, mut rocket_impulse) =
        rocket_query.single_mut();

    if colliding_entities.len() == 0 {
        rocket_transform.rotation = Quat::from_rotation_z(input.rotation + state.offset);
    } else {
        state.offset = rocket_transform.rotation.to_euler(EulerRot::YXZ).2 - input.rotation;
        println!("Rotation: {}", state.offset);
    }

    // a = b + x

    if input.thrust {
        let mut force = Vec2::new(0.0, game_config.thrust_value);

        // shoot a ray of length thrustDistance in the direction downwards from the rocket
        let ray_origin = rocket_transform.translation.truncate();
        let ray_dir = rocket_transform
            .rotation
            .mul_vec3(Vec3::new(0.0, -1.0, 0.0))
            .truncate();

        let max_toi = game_config.thrust_distance * 3.6 + 3.6 * 0.5;

        println!("Ray origin: {:?}, dir: {:?}", ray_origin, ray_dir);

        if let Some(_) = rapier_context.cast_ray(
            ray_origin,
            ray_dir,
            max_toi,
            false,
            QueryFilter::default().exclude_rigid_body(entity),
        ) {
            println!("Hit ground!");
            force *= game_config.thrust_ground_multiplier;
        }

        let rotated_force = rocket_transform.rotation * force.extend(0.0);
        // println!("Force: {:?}", rotated_force);
        rocket_impulse.impulse = rotated_force.truncate()
    }
}
*/
