[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
bevy = "0.12.1"
bevy_prototype_lyon = "0.10.0"
bevy_rapier2d = { version = "0.23.0", features = ["wasm-bindgen", "enhanced-determinism"] }
half = "2.3.1"
i_float = "0.6.0"
i_overlay = "0.13.0"
i_shape = "0.9.0"
i_triangle = "0.11.0"
js-sys = "0.3.66"
prost = "0.12.3"
rapier2d = { version = "0.17.2", features = ["enhanced-determinism", "wasm-bindgen"] }
rust-proto = { version = "0.1.0", path = "../rust-proto" }
wasm-bindgen = "0.2.89"
