[workspace]

[package]
name = "rust-game-rl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.1", features = ["serialize"] }
burn = { version = "0.12.1", features = ["wgpu", "autodiff", "vision"] }
rand = "0.8.5"
serde = "1.0.197"
 