name = "rocket-game-worker"
main = "src/index.ts"
compatibility_date = "2023-09-08"

# usage_model = "unbound"
compatibility_flags = [ "nodejs_compat" ]

[dev]
port = 3002

[env]
CLIENT_URL="https://new.rocketgame.app"
