name = "rocket-game-worker"
main = "src/index.ts"
  compatibility_date = "2024-03-04"

compatibility_flags = [ "nodejs_compat" ]

usage_model = "unbound"

[dev]
port = 3002

[vars]
CLIENT_URL = "https://new.rocketgame.app"

[[d1_databases]]
migrations_dir = "drizzle"
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "rocket-game-d1"
database_id = "0057ecf2-ede7-4876-ba0d-4542a665d209"
