name = "rocket-game-worker"
main = "src/index.ts"
compatibility_date = "2023-09-08"

compatibility_flags = [ "nodejs_compat" ]

usage_model = "unbound"

[dev]
port = 3002

[vars]
CLIENT_URL = "https://new.rocketgame.app"

[[d1_databases]]
migrations_dir = "drizzle"
binding = "DB"
database_name = "rocket-game-d1"
database_id = "d64d6d5a-6daa-434c-94e1-8412c195f839"
